### ISSUE TITLE
Does ruport gem work's fine on ruby 1.9 > ?

### ISSUE THREAD

**Issue by deepakhb2** [ruport/ruport#28]
I faced many issues while generating PDF report on ruby 1.9.3 but the same will work fine on ruby 1.8.7
ref: https://github.com/deepakhb2/ruport-examples

example error: pdf-writer-1.1.8/lib/pdf/writer.rb:2375:in `text': undefined method`each' for "<i>Rinara Productions</i>, <i>Sample Document</i>":String (NoMethodError)

**Comment by mk-qi** [comment]
i am  sure it can not  running well  on   ruby 2.0 > ?
alwasy  tell me  

faster_csv.rb:2001: warning: already initialized constant FCSV
ruport.rb:18: warning: previous definition of FCSV was here
NotImplementedError: Please switch to Ruby 1.9's standard CSV library. It's FasterCSV plus support for Ruby 1.9's m17n encoding engine.

egrep  -r  'fastercsv' ./  
.//lib/ruport/data/table.rb:        require "fastercsv"
.//lib/ruport/formatter/csv.rb:      require "fastercsv" unless RUBY_VERSION > "1.9"   
.//Rakefile:    gemspec.add_dependency 'fastercsv'

**Comment by KranthiKishore** [comment]
Hi @mk-qi Yeah,  I'm also facing the same issues when upgraging from ruby 1.8.7 - 2.x and rails 2 - 4.x. Did you find any alternative for this or solved those issues in any other way?

**Comment by Odaeus** [comment]
The latest on the master branch from GitHub should have fixes for all these issues. I haven't released it because I'm not confident there aren't breaking changes. I'd be grateful if all of you could test it by setting your Gemfile to pull from this repo with `gem "ruport", git: "https://github.com/ruport/ruport.git"` and let me know if it works fine for you?

**Comment by KranthiKishore** [comment]
@Odaeus Definitely. Will use it and update you!. Thanks for your prompt reply! :smile:

**Comment by sshaw** [comment]
@Odaeus given this fix and #30 (possibly others), can you just make a new release?

**Comment by Odaeus** [comment]
@sshaw wish granted! 😄   No one came forward to actually test it works in their project, and I haven't needed to use it in many years, but the tests pass so I've released 1.7.0.

**Comment by kbrock** [comment]
Supporting all currently supported versions of rails and ruby
