### ISSUE TITLE
Kernel.Table method collides with global Table-method of Arel in Rails3

### ISSUE THREAD

**Issue by akafred** [ruport/ruport#3]
Kernel.Table method collides with global Table-method of Arel in Rails3. The global Table-method can in client code be replaced by Ruport::Data::Table.new (which has a different interface) - but methods like Pivot.to_table uses the Kernel.Table method and is broken (because Arels Table method interferes).

**Comment by kbrock** [comment]
The `Table` references have been cleaned up

This works with recent versions of rails
