### ISSUE TITLE
Integrate Gemnasium and Coverall services

### ISSUE THREAD

**Issue by saveriomiroddi** [ruport/ruport#48]
- [x] ~give permissions~
- [x] setup services
- [x] add coverall badge to README (see #49)
- [x] ~add gemnasium badge to README~

**Comment by saveriomiroddi** [comment]
@Odaeus I've found that giving permissions requires being an owner, so you'll need to do that :smile:
Also, I think coveralls would be a good addition, to see what is covered and what not.

**Comment by saveriomiroddi** [comment]
@Odaeus Can you also give Gemnasium the permission to create the webhook? if it's a problem to give write permissions (given how Github currently works, the granularity is very coarse), I can manually perform the gems scanning! :+1:

**Comment by Odaeus** [comment]
@saveriomiroddi 🤔  happy to do that but I dunno how, I've already given Gemnasium org access. I can "add the service" manually but I need an API key. I logged into Gemnasium with my GH account but it seems it doesn't automatically share GH projects.

**Comment by saveriomiroddi** [comment]
Hehe. I had a look at the Gemnasium analysis, and once the pdf-writer is gone, the only dependency is Prawn, so there's not much to track, and possibly it's not worth putting any effort into dependency checking.

I'm going to test, over the next couple of weeks, versions 2.1.0 and the latest, 2.2.0, to make sure they work well with Ruport, then open a PR.

In the meanwhile, is there anything else, besides the cleanups of this PR, to update in the gemspec? Thanks!!

**Comment by kbrock** [comment]
Gemnasium is no longer public facing. So we can't add that.

We are using coveralls. So looks like this is all set.
